"""Public ATS job boards. No LinkedIn/Indeed scraping.

Every slug here was probed against the live API and returned postings. Dead
slugs are removed rather than left in place, because a silently-404ing board
looks identical to a board with no matching roles. `hunter boards` re-probes
these and reports anything that has gone dark.
"""

GREENHOUSE_BOARDS = [
    "affirm",
    "airbnb",
    "airtable",
    "alloy",
    "amplitude",
    "anthropic",
    "asana",
    "block",
    "braze",
    "calm",
    "carta",
    "checkr",
    "chime",
    "circleci",
    "cloudflare",
    "cockroachlabs",
    "coinbase",
    "collibra",
    "coreweave",
    "coursera",
    "databricks",
    "dataiku",
    "datadog",
    "discord",
    "doximity",
    "dropbox",
    "duolingo",
    "earnin",
    "elastic",
    "faire",
    "fastly",
    "figma",
    "fivetran",
    "flexport",
    "forter",
    "gemini",
    "gitlab",
    "glossier",
    "grafanalabs",
    "gusto",
    "hextechnologies",
    "hightouch",
    "huntress",
    "instabase",
    "instacart",
    "intercom",
    "justworks",
    "khanacademy",
    "klaviyo",
    "komodohealth",
    "lattice",
    "launchdarkly",
    "linkedin",
    "lithic",
    "lyft",
    "mercury",
    "mixpanel",
    "modernhealth",
    "mongodb",
    "motive",
    "newrelic",
    "nextdoor",
    "nuro",
    "okta",
    "outschool",
    "pendo",
    "peloton",
    "pinterest",
    "postman",
    "postscript",
    "reddit",
    "riotgames",
    "robinhood",
    "roblox",
    "samsara",
    "scaleai",
    "sigmacomputing",
    "smartsheet",
    "sofi",
    "starburst",
    "stripe",
    "tubi",
    "twilio",
    "twitch",
    "udacity",
    "udemy",
    "upgrade",
    "upstart",
    "vercel",
    "verkada",
    "via",
    "webflow",
    "wise",
    "zscaler",
]

LEVER_COMPANIES = [
    "cloudinary",
    "palantir",
    "prismic",
    "ro",
    "spotify",
    "veeva",
]

ASHBY_BOARDS = [
    "abridge",
    "airbyte",
    "astronomer",
    "attio",
    "baseten",
    "browserbase",
    "character",
    "clickhouse",
    "coder",
    "cursor",
    "deepgram",
    "e2b",
    "elevenlabs",
    "harvey",
    "hex",
    "hightouch",
    "inngest",
    "knock",
    "lightdash",
    "linear",
    "mintlify",
    "modal",
    "motherduck",
    "neon",
    "notion",
    "omni",
    "openai",
    "perplexity",
    "posthog",
    "prefect",
    "pylon",
    "railway",
    "ramp",
    "render",
    "resend",
    "runway",
    "sierra",
    "snowflake",
    "supabase",
    "temporal",
    "unify",
    "warp",
    "writer",
    "zed",
]

# (tenant, workday subdomain, career site id). Workday powers many large
# enterprises that never appear on Greenhouse or Lever.
WORKDAY_TENANTS = [
    ("adobe", "wd5", "external_experienced"),
    ("cvshealth", "wd1", "CVS_Health_Careers"),
    ("mastercard", "wd1", "CorporateCareers"),
    ("nvidia", "wd5", "NVIDIAExternalCareerSite"),
    ("paypal", "wd1", "jobs"),
    ("salesforce", "wd12", "External_Career_Site"),
    ("target", "wd5", "targetcareers"),
    ("workday", "wd5", "Workday"),
]

# Search terms sent to Workday, which requires a query rather than a full dump.
WORKDAY_QUERIES = [
    "analytics engineer",
    "analytics",
    "data engineering",
    "business intelligence",
]
